// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBF6PqX0I-vRTkuUzyCzdhbbz8neVIPWQ',
    appId: '1:674624179579:web:91995576ae2672edf801de',
    messagingSenderId: '674624179579',
    projectId: 'fir-realtime-40327',
    authDomain: 'fir-realtime-40327.firebaseapp.com',
    databaseURL: 'https://fir-realtime-40327-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-40327.appspot.com',
    measurementId: 'G-LZZT4MBG7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUy-2u5ppGBlpsHYlALq94npY4IAPoL6I',
    appId: '1:674624179579:android:525622245a5d287cf801de',
    messagingSenderId: '674624179579',
    projectId: 'fir-realtime-40327',
    databaseURL: 'https://fir-realtime-40327-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-40327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKDbM4dFEcK7s5RlOJSgD_1iGzmAeyUI',
    appId: '1:674624179579:ios:49a9db7173ee0abef801de',
    messagingSenderId: '674624179579',
    projectId: 'fir-realtime-40327',
    databaseURL: 'https://fir-realtime-40327-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-40327.appspot.com',
    iosBundleId: 'com.example.myvideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKDbM4dFEcK7s5RlOJSgD_1iGzmAeyUI',
    appId: '1:674624179579:ios:ba11262129e10cacf801de',
    messagingSenderId: '674624179579',
    projectId: 'fir-realtime-40327',
    databaseURL: 'https://fir-realtime-40327-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-40327.appspot.com',
    iosBundleId: 'com.example.myvideo.RunnerTests',
  );
}
